/*
 * System call vector from .master file for rump.
 * DO NOT EDIT-- this file is automatically generated.
 */

__SYSCALL_COMMON(0, sys_read, sys_read)
__SYSCALL_COMMON(1, sys_write, sys_write)
__SYSCALL_COMMON(3, sys_close, sys_close)
__SYSCALL_COMMON(7, sys_poll, sys_poll)
__SYSCALL_64(16, sys_ioctl, sys_ioctl)
__SYSCALL_COMMON(18, sys_pwrite64, sys_pwrite64)
__SYSCALL_64(20, sys_writev, sys_writev)
__SYSCALL_COMMON(22, sys_pipe, sys_pipe)
__SYSCALL_COMMON(23, sys_select, sys_select)
__SYSCALL_COMMON(41, sys_socket, sys_socket)
__SYSCALL_COMMON(42, sys_connect, sys_connect)
__SYSCALL_COMMON(43, sys_accept, sys_accept)
__SYSCALL_COMMON(44, sys_sendto, sys_sendto)
__SYSCALL_64(45, sys_recvfrom, sys_recvfrom)
__SYSCALL_64(46, sys_sendmsg, sys_sendmsg)
__SYSCALL_64(47, sys_recvmsg, sys_recvmsg)
__SYSCALL_COMMON(49, sys_bind, sys_bind)
__SYSCALL_COMMON(50, sys_listen, sys_listen)
__SYSCALL_COMMON(51, sys_getsockname, sys_getsockname)
__SYSCALL_COMMON(52, sys_getpeername, sys_getpeername)
__SYSCALL_64(54, sys_setsockopt, sys_setsockopt)
__SYSCALL_64(55, sys_getsockopt, sys_getsockopt)
__SYSCALL_COMMON(72, sys_fcntl, sys_fcntl)
__SYSCALL_COMMON(213, sys_epoll_create, sys_epoll_create)
__SYSCALL_COMMON(228, sys_clock_gettime, sys_clock_gettime)
__SYSCALL_COMMON(232, sys_epoll_wait, sys_epoll_wait)
__SYSCALL_COMMON(233, sys_epoll_ctl, sys_epoll_ctl)
__SYSCALL_64(296, sys_pwritev, sys_pwritev)
__SYSCALL_64(307, sys_sendmmsg, sys_sendmmsg)
#define __NR_syscall_max 545
#define NR_syscalls (__NR_syscall_max + 1)

