/*
 * System call vector and marshalling for rump.
 * DO NOT EDIT-- this file is automatically generated.
 */


#ifdef RUMP_CLIENT
#include <rump/rumpuser_port.h>
#endif /* RUMP_CLIENT */

/* XXX: FIXME to use generated syscalls_64.h */
//#include <asm/syscalls_64.h>
#include <asm/unistd_64.h>

struct pollfd;
struct epoll_event;
struct msghdr;
struct mmsghdr;
struct user_msghdr;
struct iovec;
struct sockaddr;
struct timeval;
struct timespec;


#ifdef RUMP_CLIENT
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <rump/rumpclient.h>

struct syscall_args {
	unsigned long args[6];
};

#ifndef umode_t
typedef unsigned short		umode_t;
#endif /* umode_t */

#define rsys_syscall(num, data, dlen, retval)	    rumpclient_syscall(num, data, dlen, retval)
#define rsys_seterrno(error) errno = error

#else /* !RUMP_CLIENT */

#include <linux/compiler.h>
#include <linux/types.h>
#include <linux/string.h>
#include <asm-generic/errno.h>

#ifndef __dead
#define __dead __attribute__((__noreturn__))
#endif

#ifndef __printflike
#ifdef __GNUC__
#define __printflike(a,b) __attribute__((__format__ (__printf__,a,b)))
#else
#define __printflike(a,b)
#endif
#endif

#ifndef loff_t
typedef long long      loff_t;
#endif /* loff_t */
typedef int            clockid_t;
typedef unsigned long          u_long;
typedef unsigned int           u_int;
#define RUMP_REGISTER_T long
typedef RUMP_REGISTER_T register_t;
typedef int            pid_t;


#include <generated/rump_syscalls.h>
#include <rump/rump.h>
#include <rump/rumpuser.h>
int rump_syscall(int num, void *data, size_t dlen, register_t *retval);
#define rsys_syscall(num, data, dlen, retval)	    rump_syscall(num, data, dlen, retval)

#define rsys_seterrno(error) rumpuser_seterrno(error)

#endif

/* XXX */
#define __user

#define __weak_alias(aliasname, name)						extern __typeof (name) aliasname __attribute__ ((weak, alias (# name)))
//#define __strong_alias(aliasname, name)						extern __typeof (name) aliasname __attribute__ ((strong, alias (# name)))
#define __strong_alias(aliasname, name)

#define NOT_IMPLEMENTED(x) int (x)(void){      	rsys_seterrno(ENOSYS);                 	return -1;                                     }

NOT_IMPLEMENTED(rump___sysimpl_pollts50)
NOT_IMPLEMENTED(rump___sysimpl_lchmod)
NOT_IMPLEMENTED(rump___sysimpl_lutimes50)
NOT_IMPLEMENTED(rump___sysimpl_futimes50)
NOT_IMPLEMENTED(rump___sysimpl_futimens)

long rump___sysimpl_read(unsigned int fd, char __user * buf, size_t count);
long
rump___sysimpl_read(unsigned int fd,  char __user * buf,  size_t count)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)buf;
	callarg.args[2] = (unsigned long)count;
	error = rsys_syscall(__NR_read, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(read,rump___sysimpl_read);
__weak_alias(_read,rump___sysimpl_read);
__strong_alias(_sys_read,rump___sysimpl_read);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_write(unsigned int fd, const char __user * buf, size_t count);
long
rump___sysimpl_write(unsigned int fd,  const char __user * buf,  size_t count)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)buf;
	callarg.args[2] = (unsigned long)count;
	error = rsys_syscall(__NR_write, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(write,rump___sysimpl_write);
__weak_alias(_write,rump___sysimpl_write);
__strong_alias(_sys_write,rump___sysimpl_write);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_open(const char __user * filename, int flags, umode_t mode);
long
rump___sysimpl_open(const char __user * filename,  int flags,  umode_t mode)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)filename;
	callarg.args[1] = (unsigned long)flags;
	callarg.args[2] = (unsigned long)mode;
	error = rsys_syscall(__NR_open, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(open,rump___sysimpl_open);
__weak_alias(_open,rump___sysimpl_open);
__strong_alias(_sys_open,rump___sysimpl_open);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_close(unsigned int fd);
long
rump___sysimpl_close(unsigned int fd)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	error = rsys_syscall(__NR_close, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(close,rump___sysimpl_close);
__weak_alias(_close,rump___sysimpl_close);
__strong_alias(_sys_close,rump___sysimpl_close);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_stat)

NOT_IMPLEMENTED(rump___sysimpl_fstat)

NOT_IMPLEMENTED(rump___sysimpl_lstat)

long rump___sysimpl_poll(struct pollfd __user * ufds, unsigned int nfds, int timeout);
long
rump___sysimpl_poll(struct pollfd __user * ufds,  unsigned int nfds,  int timeout)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)ufds;
	callarg.args[1] = (unsigned long)nfds;
	callarg.args[2] = (unsigned long)timeout;
	error = rsys_syscall(__NR_poll, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(poll,rump___sysimpl_poll);
__weak_alias(_poll,rump___sysimpl_poll);
__strong_alias(_sys_poll,rump___sysimpl_poll);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_lseek)

NOT_IMPLEMENTED(rump___sysimpl_mmap)

NOT_IMPLEMENTED(rump___sysimpl_mprotect)

NOT_IMPLEMENTED(rump___sysimpl_munmap)

NOT_IMPLEMENTED(rump___sysimpl_brk)

NOT_IMPLEMENTED(rump___sysimpl_rt_sigaction)

NOT_IMPLEMENTED(rump___sysimpl_rt_sigprocmask)

NOT_IMPLEMENTED(rump___sysimpl_rt_sigreturn)

long rump___sysimpl_ioctl(unsigned int fd, unsigned int cmd, unsigned long arg);
long
rump___sysimpl_ioctl(unsigned int fd,  unsigned int cmd,  unsigned long arg)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)cmd;
	callarg.args[2] = (unsigned long)arg;
	error = rsys_syscall(__NR_ioctl, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(ioctl,rump___sysimpl_ioctl);
__weak_alias(_ioctl,rump___sysimpl_ioctl);
__strong_alias(_sys_ioctl,rump___sysimpl_ioctl);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_pread64)

long rump___sysimpl_pwrite64(unsigned int fd, const char __user * buf, size_t count, loff_t pos);
long
rump___sysimpl_pwrite64(unsigned int fd,  const char __user * buf,  size_t count,  loff_t pos)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)buf;
	callarg.args[2] = (unsigned long)count;
	callarg.args[3] = (unsigned long)pos;
	error = rsys_syscall(__NR_pwrite64, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(pwrite64,rump___sysimpl_pwrite64);
__weak_alias(_pwrite64,rump___sysimpl_pwrite64);
__strong_alias(_sys_pwrite64,rump___sysimpl_pwrite64);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_readv)

long rump___sysimpl_writev(unsigned long fd, const struct iovec __user * vec, unsigned long vlen);
long
rump___sysimpl_writev(unsigned long fd,  const struct iovec __user * vec,  unsigned long vlen)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)vec;
	callarg.args[2] = (unsigned long)vlen;
	error = rsys_syscall(__NR_writev, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(writev,rump___sysimpl_writev);
__weak_alias(_writev,rump___sysimpl_writev);
__strong_alias(_sys_writev,rump___sysimpl_writev);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_access)

long rump___sysimpl_pipe(int __user * fildes);
long
rump___sysimpl_pipe(int __user * fildes)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fildes;
	error = rsys_syscall(__NR_pipe, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(pipe,rump___sysimpl_pipe);
__weak_alias(_pipe,rump___sysimpl_pipe);
__strong_alias(_sys_pipe,rump___sysimpl_pipe);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_select(int n, fd_set __user * inp, fd_set __user * outp, fd_set __user * exp, struct timeval __user * tvp);
long
rump___sysimpl_select(int n,  fd_set __user * inp,  fd_set __user * outp,  fd_set __user * exp,  struct timeval __user * tvp)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)n;
	callarg.args[1] = (unsigned long)inp;
	callarg.args[2] = (unsigned long)outp;
	callarg.args[3] = (unsigned long)exp;
	callarg.args[4] = (unsigned long)tvp;
	error = rsys_syscall(__NR_select, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(select,rump___sysimpl_select);
__weak_alias(_select,rump___sysimpl_select);
__strong_alias(_sys_select,rump___sysimpl_select);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_sched_yield)

NOT_IMPLEMENTED(rump___sysimpl_mremap)

NOT_IMPLEMENTED(rump___sysimpl_msync)

NOT_IMPLEMENTED(rump___sysimpl_mincore)

NOT_IMPLEMENTED(rump___sysimpl_madvise)

NOT_IMPLEMENTED(rump___sysimpl_shmget)

NOT_IMPLEMENTED(rump___sysimpl_shmat)

NOT_IMPLEMENTED(rump___sysimpl_shmctl)

NOT_IMPLEMENTED(rump___sysimpl_dup)

NOT_IMPLEMENTED(rump___sysimpl_dup2)

NOT_IMPLEMENTED(rump___sysimpl_pause)

long rump___sysimpl_nanosleep(struct timespec __user * rqtp, struct timespec __user * rmtp);
long
rump___sysimpl_nanosleep(struct timespec __user * rqtp,  struct timespec __user * rmtp)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)rqtp;
	callarg.args[1] = (unsigned long)rmtp;
	error = rsys_syscall(__NR_nanosleep, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(nanosleep,rump___sysimpl_nanosleep);
__weak_alias(_nanosleep,rump___sysimpl_nanosleep);
__strong_alias(_sys_nanosleep,rump___sysimpl_nanosleep);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_getitimer)

NOT_IMPLEMENTED(rump___sysimpl_alarm)

NOT_IMPLEMENTED(rump___sysimpl_setitimer)

long rump___sysimpl_getpid(void);
long
rump___sysimpl_getpid()
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	error = rsys_syscall(__NR_getpid, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(getpid,rump___sysimpl_getpid);
__weak_alias(_getpid,rump___sysimpl_getpid);
__strong_alias(_sys_getpid,rump___sysimpl_getpid);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_sendfile)

long rump___sysimpl_socket(int, int, int);
long
rump___sysimpl_socket(int arg1, int arg2, int arg3)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	callarg.args[2] = (unsigned long)arg3;
	error = rsys_syscall(__NR_socket, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(socket,rump___sysimpl_socket);
__weak_alias(_socket,rump___sysimpl_socket);
__strong_alias(_sys_socket,rump___sysimpl_socket);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_connect(int, struct sockaddr __user *, int);
long
rump___sysimpl_connect(int arg1,  struct sockaddr __user * arg2, int arg3)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	callarg.args[2] = (unsigned long)arg3;
	error = rsys_syscall(__NR_connect, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(connect,rump___sysimpl_connect);
__weak_alias(_connect,rump___sysimpl_connect);
__strong_alias(_sys_connect,rump___sysimpl_connect);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_accept(int, struct sockaddr __user *, int __user *);
long
rump___sysimpl_accept(int arg1,  struct sockaddr __user * arg2,  int __user * arg3)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	callarg.args[2] = (unsigned long)arg3;
	error = rsys_syscall(__NR_accept, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(accept,rump___sysimpl_accept);
__weak_alias(_accept,rump___sysimpl_accept);
__strong_alias(_sys_accept,rump___sysimpl_accept);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_sendto(int, void __user *, size_t, unsigned,                           struct sockaddr __user *, int);
long
rump___sysimpl_sendto(int arg1,  void __user * arg2, size_t arg3, unsigned arg4,                            struct sockaddr __user * arg5, int arg6)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	callarg.args[2] = (unsigned long)arg3;
	callarg.args[3] = (unsigned long)arg4;
	callarg.args[4] = (unsigned long)arg5;
	callarg.args[5] = (unsigned long)arg6;
	error = rsys_syscall(__NR_sendto, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(sendto,rump___sysimpl_sendto);
__weak_alias(_sendto,rump___sysimpl_sendto);
__strong_alias(_sys_sendto,rump___sysimpl_sendto);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_recvfrom(int, void __user *, size_t, unsigned,                             struct sockaddr __user *, int __user *);
long
rump___sysimpl_recvfrom(int arg1,  void __user * arg2, size_t arg3, unsigned arg4,                              struct sockaddr __user * arg5,  int __user * arg6)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	callarg.args[2] = (unsigned long)arg3;
	callarg.args[3] = (unsigned long)arg4;
	callarg.args[4] = (unsigned long)arg5;
	callarg.args[5] = (unsigned long)arg6;
	error = rsys_syscall(__NR_recvfrom, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(recvfrom,rump___sysimpl_recvfrom);
__weak_alias(_recvfrom,rump___sysimpl_recvfrom);
__strong_alias(_sys_recvfrom,rump___sysimpl_recvfrom);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_sendmsg(int fd, struct user_msghdr __user * msg, unsigned flags);
long
rump___sysimpl_sendmsg(int fd,  struct user_msghdr __user * msg,  unsigned flags)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)msg;
	callarg.args[2] = (unsigned long)flags;
	error = rsys_syscall(__NR_sendmsg, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(sendmsg,rump___sysimpl_sendmsg);
__weak_alias(_sendmsg,rump___sysimpl_sendmsg);
__strong_alias(_sys_sendmsg,rump___sysimpl_sendmsg);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_recvmsg(int fd, struct user_msghdr __user * msg, unsigned flags);
long
rump___sysimpl_recvmsg(int fd,  struct user_msghdr __user * msg,  unsigned flags)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)msg;
	callarg.args[2] = (unsigned long)flags;
	error = rsys_syscall(__NR_recvmsg, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(recvmsg,rump___sysimpl_recvmsg);
__weak_alias(_recvmsg,rump___sysimpl_recvmsg);
__strong_alias(_sys_recvmsg,rump___sysimpl_recvmsg);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_shutdown)

long rump___sysimpl_bind(int, struct sockaddr __user *, int);
long
rump___sysimpl_bind(int arg1,  struct sockaddr __user * arg2, int arg3)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	callarg.args[2] = (unsigned long)arg3;
	error = rsys_syscall(__NR_bind, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(bind,rump___sysimpl_bind);
__weak_alias(_bind,rump___sysimpl_bind);
__strong_alias(_sys_bind,rump___sysimpl_bind);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_listen(int, int);
long
rump___sysimpl_listen(int arg1, int arg2)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	error = rsys_syscall(__NR_listen, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(listen,rump___sysimpl_listen);
__weak_alias(_listen,rump___sysimpl_listen);
__strong_alias(_sys_listen,rump___sysimpl_listen);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_getsockname(int, struct sockaddr __user *, int __user *);
long
rump___sysimpl_getsockname(int arg1,  struct sockaddr __user * arg2,  int __user * arg3)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	callarg.args[2] = (unsigned long)arg3;
	error = rsys_syscall(__NR_getsockname, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(getsockname,rump___sysimpl_getsockname);
__weak_alias(_getsockname,rump___sysimpl_getsockname);
__strong_alias(_sys_getsockname,rump___sysimpl_getsockname);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_getpeername(int, struct sockaddr __user *, int __user *);
long
rump___sysimpl_getpeername(int arg1,  struct sockaddr __user * arg2,  int __user * arg3)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)arg1;
	callarg.args[1] = (unsigned long)arg2;
	callarg.args[2] = (unsigned long)arg3;
	error = rsys_syscall(__NR_getpeername, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(getpeername,rump___sysimpl_getpeername);
__weak_alias(_getpeername,rump___sysimpl_getpeername);
__strong_alias(_sys_getpeername,rump___sysimpl_getpeername);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_socketpair)

long rump___sysimpl_setsockopt(int fd, int level, int optname, char __user * optval, int optlen);
long
rump___sysimpl_setsockopt(int fd,  int level,  int optname,  char __user * optval,  int optlen)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)level;
	callarg.args[2] = (unsigned long)optname;
	callarg.args[3] = (unsigned long)optval;
	callarg.args[4] = (unsigned long)optlen;
	error = rsys_syscall(__NR_setsockopt, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(setsockopt,rump___sysimpl_setsockopt);
__weak_alias(_setsockopt,rump___sysimpl_setsockopt);
__strong_alias(_sys_setsockopt,rump___sysimpl_setsockopt);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_getsockopt(int fd, int level, int optname, char __user * optval, int __user * optlen);
long
rump___sysimpl_getsockopt(int fd,  int level,  int optname,  char __user * optval,  int __user * optlen)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)level;
	callarg.args[2] = (unsigned long)optname;
	callarg.args[3] = (unsigned long)optval;
	callarg.args[4] = (unsigned long)optlen;
	error = rsys_syscall(__NR_getsockopt, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(getsockopt,rump___sysimpl_getsockopt);
__weak_alias(_getsockopt,rump___sysimpl_getsockopt);
__strong_alias(_sys_getsockopt,rump___sysimpl_getsockopt);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_clone)

NOT_IMPLEMENTED(rump___sysimpl_fork)

NOT_IMPLEMENTED(rump___sysimpl_vfork)

NOT_IMPLEMENTED(rump___sysimpl_execve)

NOT_IMPLEMENTED(rump___sysimpl_exit)

NOT_IMPLEMENTED(rump___sysimpl_wait4)

NOT_IMPLEMENTED(rump___sysimpl_kill)

NOT_IMPLEMENTED(rump___sysimpl_uname)

NOT_IMPLEMENTED(rump___sysimpl_semget)

NOT_IMPLEMENTED(rump___sysimpl_semop)

NOT_IMPLEMENTED(rump___sysimpl_semctl)

NOT_IMPLEMENTED(rump___sysimpl_shmdt)

NOT_IMPLEMENTED(rump___sysimpl_msgget)

NOT_IMPLEMENTED(rump___sysimpl_msgsnd)

NOT_IMPLEMENTED(rump___sysimpl_msgrcv)

NOT_IMPLEMENTED(rump___sysimpl_msgctl)

long rump___sysimpl_fcntl(unsigned int fd, unsigned int cmd, unsigned long arg);
long
rump___sysimpl_fcntl(unsigned int fd,  unsigned int cmd,  unsigned long arg)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)cmd;
	callarg.args[2] = (unsigned long)arg;
	error = rsys_syscall(__NR_fcntl, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(fcntl,rump___sysimpl_fcntl);
__weak_alias(_fcntl,rump___sysimpl_fcntl);
__strong_alias(_sys_fcntl,rump___sysimpl_fcntl);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_flock)

NOT_IMPLEMENTED(rump___sysimpl_fsync)

NOT_IMPLEMENTED(rump___sysimpl_fdatasync)

NOT_IMPLEMENTED(rump___sysimpl_truncate)

NOT_IMPLEMENTED(rump___sysimpl_ftruncate)

NOT_IMPLEMENTED(rump___sysimpl_getdents)

NOT_IMPLEMENTED(rump___sysimpl_getcwd)

NOT_IMPLEMENTED(rump___sysimpl_chdir)

NOT_IMPLEMENTED(rump___sysimpl_fchdir)

NOT_IMPLEMENTED(rump___sysimpl_rename)

NOT_IMPLEMENTED(rump___sysimpl_mkdir)

NOT_IMPLEMENTED(rump___sysimpl_rmdir)

NOT_IMPLEMENTED(rump___sysimpl_creat)

NOT_IMPLEMENTED(rump___sysimpl_link)

NOT_IMPLEMENTED(rump___sysimpl_unlink)

NOT_IMPLEMENTED(rump___sysimpl_symlink)

NOT_IMPLEMENTED(rump___sysimpl_readlink)

NOT_IMPLEMENTED(rump___sysimpl_chmod)

NOT_IMPLEMENTED(rump___sysimpl_fchmod)

NOT_IMPLEMENTED(rump___sysimpl_chown)

NOT_IMPLEMENTED(rump___sysimpl_fchown)

NOT_IMPLEMENTED(rump___sysimpl_lchown)

NOT_IMPLEMENTED(rump___sysimpl_umask)

NOT_IMPLEMENTED(rump___sysimpl_gettimeofday)

NOT_IMPLEMENTED(rump___sysimpl_getrlimit)

NOT_IMPLEMENTED(rump___sysimpl_getrusage)

NOT_IMPLEMENTED(rump___sysimpl_sysinfo)

NOT_IMPLEMENTED(rump___sysimpl_times)

NOT_IMPLEMENTED(rump___sysimpl_ptrace)

NOT_IMPLEMENTED(rump___sysimpl_getuid)

NOT_IMPLEMENTED(rump___sysimpl_syslog)

NOT_IMPLEMENTED(rump___sysimpl_getgid)

NOT_IMPLEMENTED(rump___sysimpl_setuid)

NOT_IMPLEMENTED(rump___sysimpl_setgid)

NOT_IMPLEMENTED(rump___sysimpl_geteuid)

NOT_IMPLEMENTED(rump___sysimpl_getegid)

NOT_IMPLEMENTED(rump___sysimpl_setpgid)

NOT_IMPLEMENTED(rump___sysimpl_getppid)

NOT_IMPLEMENTED(rump___sysimpl_getpgrp)

NOT_IMPLEMENTED(rump___sysimpl_setsid)

NOT_IMPLEMENTED(rump___sysimpl_setreuid)

NOT_IMPLEMENTED(rump___sysimpl_setregid)

NOT_IMPLEMENTED(rump___sysimpl_getgroups)

NOT_IMPLEMENTED(rump___sysimpl_setgroups)

NOT_IMPLEMENTED(rump___sysimpl_setresuid)

NOT_IMPLEMENTED(rump___sysimpl_getresuid)

NOT_IMPLEMENTED(rump___sysimpl_setresgid)

NOT_IMPLEMENTED(rump___sysimpl_getresgid)

NOT_IMPLEMENTED(rump___sysimpl_getpgid)

NOT_IMPLEMENTED(rump___sysimpl_setfsuid)

NOT_IMPLEMENTED(rump___sysimpl_setfsgid)

NOT_IMPLEMENTED(rump___sysimpl_getsid)

NOT_IMPLEMENTED(rump___sysimpl_capget)

NOT_IMPLEMENTED(rump___sysimpl_capset)

NOT_IMPLEMENTED(rump___sysimpl_rt_sigpending)

NOT_IMPLEMENTED(rump___sysimpl_rt_sigtimedwait)

NOT_IMPLEMENTED(rump___sysimpl_rt_sigqueueinfo)

NOT_IMPLEMENTED(rump___sysimpl_rt_sigsuspend)

NOT_IMPLEMENTED(rump___sysimpl_sigaltstack)

NOT_IMPLEMENTED(rump___sysimpl_utime)

NOT_IMPLEMENTED(rump___sysimpl_mknod)

NOT_IMPLEMENTED(rump___sysimpl_uselib)

NOT_IMPLEMENTED(rump___sysimpl_personality)

NOT_IMPLEMENTED(rump___sysimpl_ustat)

NOT_IMPLEMENTED(rump___sysimpl_statfs)

NOT_IMPLEMENTED(rump___sysimpl_fstatfs)

NOT_IMPLEMENTED(rump___sysimpl_sysfs)

NOT_IMPLEMENTED(rump___sysimpl_getpriority)

NOT_IMPLEMENTED(rump___sysimpl_setpriority)

NOT_IMPLEMENTED(rump___sysimpl_sched_setparam)

NOT_IMPLEMENTED(rump___sysimpl_sched_getparam)

NOT_IMPLEMENTED(rump___sysimpl_sched_setscheduler)

NOT_IMPLEMENTED(rump___sysimpl_sched_getscheduler)

NOT_IMPLEMENTED(rump___sysimpl_sched_get_priority_max)

NOT_IMPLEMENTED(rump___sysimpl_sched_get_priority_min)

NOT_IMPLEMENTED(rump___sysimpl_sched_rr_get_interval)

NOT_IMPLEMENTED(rump___sysimpl_mlock)

NOT_IMPLEMENTED(rump___sysimpl_munlock)

NOT_IMPLEMENTED(rump___sysimpl_mlockall)

NOT_IMPLEMENTED(rump___sysimpl_munlockall)

NOT_IMPLEMENTED(rump___sysimpl_vhangup)

NOT_IMPLEMENTED(rump___sysimpl_modify_ldt)

NOT_IMPLEMENTED(rump___sysimpl_pivot_root)

NOT_IMPLEMENTED(rump___sysimpl__sysctl)

NOT_IMPLEMENTED(rump___sysimpl_prctl)

NOT_IMPLEMENTED(rump___sysimpl_arch_prctl)

NOT_IMPLEMENTED(rump___sysimpl_adjtimex)

NOT_IMPLEMENTED(rump___sysimpl_setrlimit)

NOT_IMPLEMENTED(rump___sysimpl_chroot)

NOT_IMPLEMENTED(rump___sysimpl_sync)

NOT_IMPLEMENTED(rump___sysimpl_acct)

NOT_IMPLEMENTED(rump___sysimpl_settimeofday)

NOT_IMPLEMENTED(rump___sysimpl_mount)

NOT_IMPLEMENTED(rump___sysimpl_umount2)

NOT_IMPLEMENTED(rump___sysimpl_swapon)

NOT_IMPLEMENTED(rump___sysimpl_swapoff)

long rump___sysimpl_reboot(int magic1, int magic2, unsigned int cmd, void __user * arg);
long
rump___sysimpl_reboot(int magic1,  int magic2,  unsigned int cmd,  void __user * arg)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)magic1;
	callarg.args[1] = (unsigned long)magic2;
	callarg.args[2] = (unsigned long)cmd;
	callarg.args[3] = (unsigned long)arg;
	error = rsys_syscall(__NR_reboot, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(reboot,rump___sysimpl_reboot);
__weak_alias(_reboot,rump___sysimpl_reboot);
__strong_alias(_sys_reboot,rump___sysimpl_reboot);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_sethostname)

NOT_IMPLEMENTED(rump___sysimpl_setdomainname)

NOT_IMPLEMENTED(rump___sysimpl_iopl)

NOT_IMPLEMENTED(rump___sysimpl_ioperm)

NOT_IMPLEMENTED(rump___sysimpl_create_module)

NOT_IMPLEMENTED(rump___sysimpl_init_module)

NOT_IMPLEMENTED(rump___sysimpl_delete_module)

NOT_IMPLEMENTED(rump___sysimpl_get_kernel_syms)

NOT_IMPLEMENTED(rump___sysimpl_query_module)

NOT_IMPLEMENTED(rump___sysimpl_quotactl)

NOT_IMPLEMENTED(rump___sysimpl_nfsservctl)

NOT_IMPLEMENTED(rump___sysimpl_getpmsg)

NOT_IMPLEMENTED(rump___sysimpl_putpmsg)

NOT_IMPLEMENTED(rump___sysimpl_afs_syscall)

NOT_IMPLEMENTED(rump___sysimpl_tuxcall)

NOT_IMPLEMENTED(rump___sysimpl_security)

NOT_IMPLEMENTED(rump___sysimpl_gettid)

NOT_IMPLEMENTED(rump___sysimpl_readahead)

NOT_IMPLEMENTED(rump___sysimpl_setxattr)

NOT_IMPLEMENTED(rump___sysimpl_lsetxattr)

NOT_IMPLEMENTED(rump___sysimpl_fsetxattr)

NOT_IMPLEMENTED(rump___sysimpl_getxattr)

NOT_IMPLEMENTED(rump___sysimpl_lgetxattr)

NOT_IMPLEMENTED(rump___sysimpl_fgetxattr)

NOT_IMPLEMENTED(rump___sysimpl_listxattr)

NOT_IMPLEMENTED(rump___sysimpl_llistxattr)

NOT_IMPLEMENTED(rump___sysimpl_flistxattr)

NOT_IMPLEMENTED(rump___sysimpl_removexattr)

NOT_IMPLEMENTED(rump___sysimpl_lremovexattr)

NOT_IMPLEMENTED(rump___sysimpl_fremovexattr)

NOT_IMPLEMENTED(rump___sysimpl_tkill)

NOT_IMPLEMENTED(rump___sysimpl_time)

NOT_IMPLEMENTED(rump___sysimpl_futex)

NOT_IMPLEMENTED(rump___sysimpl_sched_setaffinity)

NOT_IMPLEMENTED(rump___sysimpl_sched_getaffinity)

NOT_IMPLEMENTED(rump___sysimpl_set_thread_area)

NOT_IMPLEMENTED(rump___sysimpl_io_setup)

NOT_IMPLEMENTED(rump___sysimpl_io_destroy)

NOT_IMPLEMENTED(rump___sysimpl_io_getevents)

NOT_IMPLEMENTED(rump___sysimpl_io_submit)

NOT_IMPLEMENTED(rump___sysimpl_io_cancel)

NOT_IMPLEMENTED(rump___sysimpl_get_thread_area)

NOT_IMPLEMENTED(rump___sysimpl_lookup_dcookie)

long rump___sysimpl_epoll_create(int size);
long
rump___sysimpl_epoll_create(int size)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)size;
	error = rsys_syscall(__NR_epoll_create, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(epoll_create,rump___sysimpl_epoll_create);
__weak_alias(_epoll_create,rump___sysimpl_epoll_create);
__strong_alias(_sys_epoll_create,rump___sysimpl_epoll_create);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_epoll_ctl_old)

NOT_IMPLEMENTED(rump___sysimpl_epoll_wait_old)

NOT_IMPLEMENTED(rump___sysimpl_remap_file_pages)

NOT_IMPLEMENTED(rump___sysimpl_getdents64)

NOT_IMPLEMENTED(rump___sysimpl_set_tid_address)

NOT_IMPLEMENTED(rump___sysimpl_restart_syscall)

NOT_IMPLEMENTED(rump___sysimpl_semtimedop)

NOT_IMPLEMENTED(rump___sysimpl_fadvise64)

NOT_IMPLEMENTED(rump___sysimpl_timer_create)

NOT_IMPLEMENTED(rump___sysimpl_timer_settime)

NOT_IMPLEMENTED(rump___sysimpl_timer_gettime)

NOT_IMPLEMENTED(rump___sysimpl_timer_getoverrun)

NOT_IMPLEMENTED(rump___sysimpl_timer_delete)

NOT_IMPLEMENTED(rump___sysimpl_clock_settime)

long rump___sysimpl_clock_gettime(clockid_t which_clock, struct timespec __user * tp);
long
rump___sysimpl_clock_gettime(clockid_t which_clock,  struct timespec __user * tp)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)which_clock;
	callarg.args[1] = (unsigned long)tp;
	error = rsys_syscall(__NR_clock_gettime, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(clock_gettime,rump___sysimpl_clock_gettime);
__weak_alias(_clock_gettime,rump___sysimpl_clock_gettime);
__strong_alias(_sys_clock_gettime,rump___sysimpl_clock_gettime);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_clock_getres)

NOT_IMPLEMENTED(rump___sysimpl_clock_nanosleep)

NOT_IMPLEMENTED(rump___sysimpl_exit_group)

long rump___sysimpl_epoll_wait(int epfd, struct epoll_event __user * events, int maxevents, int timeout);
long
rump___sysimpl_epoll_wait(int epfd,  struct epoll_event __user * events,  int maxevents,  int timeout)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)epfd;
	callarg.args[1] = (unsigned long)events;
	callarg.args[2] = (unsigned long)maxevents;
	callarg.args[3] = (unsigned long)timeout;
	error = rsys_syscall(__NR_epoll_wait, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(epoll_wait,rump___sysimpl_epoll_wait);
__weak_alias(_epoll_wait,rump___sysimpl_epoll_wait);
__strong_alias(_sys_epoll_wait,rump___sysimpl_epoll_wait);
#endif /* RUMP_KERNEL_IS_LIBC */

long rump___sysimpl_epoll_ctl(int epfd, int op, int fd, struct epoll_event __user * event);
long
rump___sysimpl_epoll_ctl(int epfd,  int op,  int fd,  struct epoll_event __user * event)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)epfd;
	callarg.args[1] = (unsigned long)op;
	callarg.args[2] = (unsigned long)fd;
	callarg.args[3] = (unsigned long)event;
	error = rsys_syscall(__NR_epoll_ctl, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(epoll_ctl,rump___sysimpl_epoll_ctl);
__weak_alias(_epoll_ctl,rump___sysimpl_epoll_ctl);
__strong_alias(_sys_epoll_ctl,rump___sysimpl_epoll_ctl);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_tgkill)

NOT_IMPLEMENTED(rump___sysimpl_utimes)

NOT_IMPLEMENTED(rump___sysimpl_vserver)

NOT_IMPLEMENTED(rump___sysimpl_mbind)

NOT_IMPLEMENTED(rump___sysimpl_set_mempolicy)

NOT_IMPLEMENTED(rump___sysimpl_get_mempolicy)

NOT_IMPLEMENTED(rump___sysimpl_mq_open)

NOT_IMPLEMENTED(rump___sysimpl_mq_unlink)

NOT_IMPLEMENTED(rump___sysimpl_mq_timedsend)

NOT_IMPLEMENTED(rump___sysimpl_mq_timedreceive)

NOT_IMPLEMENTED(rump___sysimpl_mq_notify)

NOT_IMPLEMENTED(rump___sysimpl_mq_getsetattr)

NOT_IMPLEMENTED(rump___sysimpl_kexec_load)

NOT_IMPLEMENTED(rump___sysimpl_waitid)

NOT_IMPLEMENTED(rump___sysimpl_add_key)

NOT_IMPLEMENTED(rump___sysimpl_request_key)

NOT_IMPLEMENTED(rump___sysimpl_keyctl)

NOT_IMPLEMENTED(rump___sysimpl_ioprio_set)

NOT_IMPLEMENTED(rump___sysimpl_ioprio_get)

NOT_IMPLEMENTED(rump___sysimpl_inotify_init)

NOT_IMPLEMENTED(rump___sysimpl_inotify_add_watch)

NOT_IMPLEMENTED(rump___sysimpl_inotify_rm_watch)

NOT_IMPLEMENTED(rump___sysimpl_migrate_pages)

NOT_IMPLEMENTED(rump___sysimpl_openat)

NOT_IMPLEMENTED(rump___sysimpl_mkdirat)

NOT_IMPLEMENTED(rump___sysimpl_mknodat)

NOT_IMPLEMENTED(rump___sysimpl_fchownat)

NOT_IMPLEMENTED(rump___sysimpl_futimesat)

NOT_IMPLEMENTED(rump___sysimpl_newfstatat)

NOT_IMPLEMENTED(rump___sysimpl_unlinkat)

NOT_IMPLEMENTED(rump___sysimpl_renameat)

NOT_IMPLEMENTED(rump___sysimpl_linkat)

NOT_IMPLEMENTED(rump___sysimpl_symlinkat)

NOT_IMPLEMENTED(rump___sysimpl_readlinkat)

NOT_IMPLEMENTED(rump___sysimpl_fchmodat)

NOT_IMPLEMENTED(rump___sysimpl_faccessat)

NOT_IMPLEMENTED(rump___sysimpl_pselect6)

NOT_IMPLEMENTED(rump___sysimpl_ppoll)

NOT_IMPLEMENTED(rump___sysimpl_unshare)

NOT_IMPLEMENTED(rump___sysimpl_set_robust_list)

NOT_IMPLEMENTED(rump___sysimpl_get_robust_list)

NOT_IMPLEMENTED(rump___sysimpl_splice)

NOT_IMPLEMENTED(rump___sysimpl_tee)

NOT_IMPLEMENTED(rump___sysimpl_sync_file_range)

NOT_IMPLEMENTED(rump___sysimpl_vmsplice)

NOT_IMPLEMENTED(rump___sysimpl_move_pages)

NOT_IMPLEMENTED(rump___sysimpl_utimensat)

NOT_IMPLEMENTED(rump___sysimpl_epoll_pwait)

NOT_IMPLEMENTED(rump___sysimpl_signalfd)

NOT_IMPLEMENTED(rump___sysimpl_timerfd_create)

NOT_IMPLEMENTED(rump___sysimpl_eventfd)

NOT_IMPLEMENTED(rump___sysimpl_fallocate)

NOT_IMPLEMENTED(rump___sysimpl_timerfd_settime)

NOT_IMPLEMENTED(rump___sysimpl_timerfd_gettime)

NOT_IMPLEMENTED(rump___sysimpl_accept4)

NOT_IMPLEMENTED(rump___sysimpl_signalfd4)

NOT_IMPLEMENTED(rump___sysimpl_eventfd2)

NOT_IMPLEMENTED(rump___sysimpl_epoll_create1)

NOT_IMPLEMENTED(rump___sysimpl_dup3)

NOT_IMPLEMENTED(rump___sysimpl_pipe2)

NOT_IMPLEMENTED(rump___sysimpl_inotify_init1)

NOT_IMPLEMENTED(rump___sysimpl_preadv)

long rump___sysimpl_pwritev(unsigned long fd, const struct iovec __user * vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h);
long
rump___sysimpl_pwritev(unsigned long fd,  const struct iovec __user * vec,  unsigned long vlen,  unsigned long pos_l,  unsigned long pos_h)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)vec;
	callarg.args[2] = (unsigned long)vlen;
	callarg.args[3] = (unsigned long)pos_l;
	callarg.args[4] = (unsigned long)pos_h;
	error = rsys_syscall(__NR_pwritev, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(pwritev,rump___sysimpl_pwritev);
__weak_alias(_pwritev,rump___sysimpl_pwritev);
__strong_alias(_sys_pwritev,rump___sysimpl_pwritev);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_rt_tgsigqueueinfo)

NOT_IMPLEMENTED(rump___sysimpl_perf_event_open)

NOT_IMPLEMENTED(rump___sysimpl_recvmmsg)

NOT_IMPLEMENTED(rump___sysimpl_fanotify_init)

NOT_IMPLEMENTED(rump___sysimpl_fanotify_mark)

NOT_IMPLEMENTED(rump___sysimpl_prlimit64)

NOT_IMPLEMENTED(rump___sysimpl_name_to_handle_at)

NOT_IMPLEMENTED(rump___sysimpl_open_by_handle_at)

NOT_IMPLEMENTED(rump___sysimpl_clock_adjtime)

NOT_IMPLEMENTED(rump___sysimpl_syncfs)

long rump___sysimpl_sendmmsg(int fd, struct mmsghdr __user * msg, unsigned int vlen, unsigned flags);
long
rump___sysimpl_sendmmsg(int fd,  struct mmsghdr __user * msg,  unsigned int vlen,  unsigned flags)
{
	register_t retval[2];
	int error = 0;
	struct syscall_args callarg;

	memset(&callarg, 0, sizeof(callarg));
	callarg.args[0] = (unsigned long)fd;
	callarg.args[1] = (unsigned long)msg;
	callarg.args[2] = (unsigned long)vlen;
	callarg.args[3] = (unsigned long)flags;
	error = rsys_syscall(__NR_sendmmsg, &callarg, sizeof(callarg), retval);
	if (error < 0)
		rsys_seterrno(retval[0]);
	return error;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(sendmmsg,rump___sysimpl_sendmmsg);
__weak_alias(_sendmmsg,rump___sysimpl_sendmmsg);
__strong_alias(_sys_sendmmsg,rump___sysimpl_sendmmsg);
#endif /* RUMP_KERNEL_IS_LIBC */

NOT_IMPLEMENTED(rump___sysimpl_setns)

NOT_IMPLEMENTED(rump___sysimpl_getcpu)

NOT_IMPLEMENTED(rump___sysimpl_process_vm_readv)

NOT_IMPLEMENTED(rump___sysimpl_process_vm_writev)

NOT_IMPLEMENTED(rump___sysimpl_kcmp)

NOT_IMPLEMENTED(rump___sysimpl_finit_module)

NOT_IMPLEMENTED(rump___sysimpl_sched_setattr)

NOT_IMPLEMENTED(rump___sysimpl_sched_getattr)

NOT_IMPLEMENTED(rump___sysimpl_renameat2)

NOT_IMPLEMENTED(rump___sysimpl_seccomp)

NOT_IMPLEMENTED(rump___sysimpl_getrandom)

NOT_IMPLEMENTED(rump___sysimpl_memfd_create)

NOT_IMPLEMENTED(rump___sysimpl_kexec_file_load)

NOT_IMPLEMENTED(rump___sysimpl_bpf)

NOT_IMPLEMENTED(rump___sysimpl_execveat)

NOT_IMPLEMENTED(rump___sysimpl_userfaultfd)

NOT_IMPLEMENTED(rump___sysimpl_membarrier)


/* For hijack.c compatibility of NetBSD */
__weak_alias(rump___sysimpl_socket30,rump___sysimpl_socket);
__weak_alias(rump___sysimpl_pwrite,rump___sysimpl_pwrite64);
__weak_alias(rump___sysimpl_pread,rump___sysimpl_pread64);
__weak_alias(rump___sysimpl_utimes50,rump___sysimpl_utimes);
__weak_alias(rump___sysimpl_nanosleep50,rump___sysimpl_nanosleep);

