obj-y = lib.o lib-device.o lib-socket.o random.o softirq.o
obj-y += time.o timer.o hrtimer.o sched.o workqueue.o
obj-y += print.o slab.o tasklet.o tasklet-hrtimer.o
obj-y += glue.o fs.o sysctl.o proc.o sysfs.o
obj-y += capability.o pid.o modules.o filemap.o vmscan.o

#obj-y += ../../kernel/notifier.o
#params.o sysctl.o \


